name: CI/CD for react books

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          npm install
      - name: Install backend dependencies
        working-directory: ./src/backend
        run: |
            npm install
        
      - name: Build frontend
        run: npm run build
  
  #test job
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          npm install
      - name: Install backend dependencies
        working-directory: ./src/backend
        run: |
            npm install
            
      - name: Rebuild bcrypt for current OS
        working-directory: ./src/backend
        run: |
          npm rebuild bcrypt --update-binary

      - name: Run test backend
        working-directory: ./src/backend
<<<<<<< HEAD
        run: npm test -- --watchAll=false
=======
        run: npm test --watchAll=false
>>>>>>> 509f327ebc2dc9a80e5142385b19359a491d7a53
